# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
favicon: "assets/media/icons/icon.png"
font_size: xl
scripts:
  custom:
    - js/scroll-slow.js
sharing: false
# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    highlight_active_link: true
    logo:
      text: "Jeon Ho Kang"
    
# Site footer
footer:
  copyright:
    notice: '© {year} Jeon Kang.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false


# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

opengraph:
  description: "Jeon Ho Kang Personal Website"
  
# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

